name: bargainbites
description: "Marketplace that helps reducing food waste"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.1

#------------------ PACKAGES -------------------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.2.6

  # Icons
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  # State Management (GetX)
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific

#------------------- ./ PACKAGES END --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

#------------------ LOCAL ASSETS -------------------------#

  assets:
    - assets/logos/
#    - assets/icons/
#    - assets/images/

#------------------ LOCAL FONTS -------------------------#

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins/Poppins-Black.ttf
        weight: 900