// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIKCQo4cGPwE8SlmmVh00ZWCFZyXstU7c',
    appId: '1:89131630501:android:e8fbcc0bd459569640324c',
    messagingSenderId: '89131630501',
    projectId: 'bargainbites-f6682',
    storageBucket: 'bargainbites-f6682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALUJ68fM1uF-QUr0p_eWBtY121FLVcgaM',
    appId: '1:89131630501:ios:a0d02a03b329bc4340324c',
    messagingSenderId: '89131630501',
    projectId: 'bargainbites-f6682',
    storageBucket: 'bargainbites-f6682.appspot.com',
    androidClientId: '89131630501-dkmmkjuikk0s2p1rnapu3blq6snk07gp.apps.googleusercontent.com',
    iosClientId: '89131630501-e8b21356dm8il3p4148iscf4ptdue9pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.bargainbites',
  );

}